export const users = [
  { username: 'john', password: '123', avatar: 'https://randomuser.me/api/portraits/men/1.jpg' },
  { username: 'alice', password: '123', avatar: 'https://randomuser.me/api/portraits/women/2.jpg' },
  { username: 'bob', password: '123', avatar: 'https://randomuser.me/api/portraits/men/3.jpg' },
  { username: 'claire', password: '123', avatar: 'https://randomuser.me/api/portraits/women/4.jpg' },
  { username: 'dave', password: '123', avatar: 'https://randomuser.me/api/portraits/men/5.jpg' }
];

export const posts = [
  {
    id: 1,
    username: 'john',
    image: 'https://source.unsplash.com/random/800x600?sig=1',
    caption: 'Enjoying the sunset at the beach 🌅',
    likes: 12,
    comments: [{ user: 'alice', text: 'Looks amazing!' }],
  },
  {
    id: 2,
    username: 'alice',
    image: 'https://source.unsplash.com/random/800x600?sig=2',
    caption: 'Morning coffee vibes ☕',
    likes: 8,
    comments: [{ user: 'bob', text: 'Great shot!' }],
  },
  {
    id: 3,
    username: 'bob',
    image: 'https://source.unsplash.com/random/800x600?sig=3',
    caption: 'Hiking in the mountains 🏞️',
    likes: 15,
    comments: [{ user: 'claire', text: 'I want to go there!' }],
  },
  {
    id: 4,
    username: 'claire',
    image: 'https://source.unsplash.com/random/800x600?sig=4',
    caption: 'Fresh flowers in the garden 🌼',
    likes: 20,
    comments: [{ user: 'john', text: 'So pretty!' }],
  },
  {
    id: 5,
    username: 'dave',
    image: 'https://source.unsplash.com/random/800x600?sig=5',
    caption: 'City lights at night 🌃',
    likes: 10,
    comments: [{ user: 'alice', text: 'Amazing photo!' }],
  },
  {
    id: 6,
    username: 'john',
    image: 'https://source.unsplash.com/random/800x600?sig=6',
    caption: 'Lunch time 🍝',
    likes: 5,
    comments: [{ user: 'dave', text: 'Yummy!' }],
  },
  {
    id: 7,
    username: 'alice',
    image: 'https://source.unsplash.com/random/800x600?sig=7',
    caption: 'Cute puppy 🐶',
    likes: 30,
    comments: [{ user: 'bob', text: 'Adorable!' }],
  },
  {
    id: 8,
    username: 'bob',
    image: 'https://source.unsplash.com/random/800x600?sig=8',
    caption: 'At the museum 🏛️',
    likes: 9,
    comments: [{ user: 'claire', text: 'Love art!' }],
  },
  {
    id: 9,
    username: 'claire',
    image: 'https://source.unsplash.com/random/800x600?sig=9',
    caption: 'Cozy reading nook 📖',
    likes: 11,
    comments: [{ user: 'john', text: 'Looks relaxing!' }],
  },
  {
    id: 10,
    username: 'dave',
    image: 'https://source.unsplash.com/random/800x600?sig=10',
    caption: 'Street food adventure 🌮',
    likes: 17,
    comments: [{ user: 'alice', text: 'Yum!' }],
  },
];
